test_patterns = [
  "tests/**",
  "**/test_*.py",
  "tests.py"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
enabled = true
name = "test-coverage"
