language: python
dist: xenial
python:
  - "3.5"
  - "3.7"
# commands to install dependencies
install: 
  - pip install https://github.com/WeblateOrg/weblate/archive/master.zip
  - pip install https://github.com/nijel/thepay/archive/weblate.zip
  - pip install https://github.com/nijel/fakturace/archive/master.zip
  - pip install https://github.com/WeblateOrg/hosted/archive/master.zip
  - pip install https://github.com/WeblateOrg/wlc/archive/master.zip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - ./scripts/generate-locales
  - ./manage.py check
  - python -Wd -m coverage run --source=. ./manage.py test weblate_web
  - pycodestyle .
  - flake8
after_success:
  - codecov
cache: pip
addons:
  apt:
    packages:
      - texlive-latex-recommended
      - libcairo-dev
      - gir1.2-pango-1.0
      - libgirepository1.0-dev
